### ISSUE TITLE
Why does preserve default to true?

### ISSUE THREAD

**Issue by chris-morgan** [jonathantneal/postcss-pseudo-class-any-link#8]
The only reason I can think of why preserve would default to true is developer convenience in modifying the selector in-browser, which seems a very flimsy reason. Is there something I haven’t thought of? Otherwise, it seems purely wasteful, duplicating rules to no advantage.

**Comment by jonathantneal** [comment]
That’s a good question.

I want polyfill plugins to “fall forward” so that browsers supporting `:any-link` use the original code. With how gzipping works, the duplication this shouldn’t significantly impact output size. I do want the developer to be accustomed to the standards-driven markup in devtools, and the tradeoff here is duplication of the rule in devtools, right?

Now, when this polyfill is used with something like postcss-preset-env, then as Edge adopts `:any-link` and a project’s browserslist no longer needs support for IE or older Edge, then the fallbacks should disappear. That’s what I mean by “fall forward”.
